# Generated by Django 3.1.5 on 2021-01-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcschain', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='id',
        ),
        migrations.AlterField(
            model_name='block',
            name='height',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
